[phases.setup]
nixPkgs = [
  "nodejs",
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "dbus",
  "expat",
  "xcbutil",
  "libxkbcommon",
  "mesa",
  "pango",
  "cairo",
  "gtk3"
]
